widgetTheme=widget-themes/compact
primaryColor=#1e3875
secondaryColor=#415d9e
labelColor=#ffffff
hideWhenOffline=false
contactMail=prodalum@prodalum.cl
loadingLabel=Cargando...
loginError=Error
chatHeader=Conversemos
startInfo=Completa los campos para continuar.
widgetWidth=279
widgetHeight=320
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Empezar
backLabel=Volver
initMessageBody=Hola, ¿En qué puedo ayudarte?
initMessageAuthor=Ejecutivo
chatInputLabel=Escribe tu pregunta
timeDaysAgo=día(s) atrás
timeHoursAgo=hora(s) atrás
timeMinutesAgo=minuto(s) atrás
timeSecondsAgo=segundo(s) atrás
offlineMessage=Ejecutivos desconectados
toggleSoundLabel=Sonidos
toggleScrollLabel=Scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle
endChatLabel=Terminar el Chat
endChatConfirmQuestion=¿Estás seguro?
endChatConfirm=Si
endChatCancel=Cancelar
contactHeader=Contáctanos
contactInfo=Todos los ejecutivos están desconectados, déjanos un mensaje.
contactNameLabel=Tu Nombre
contactMailLabel=Tu Correo
contactQuestionLabel=Tu mensaje
contactSendLabel=Enviar
contactSuccessHeader=Mensaje Enviado
contactSuccessMessage=Tu mensaje ha sido enviado, te responderemos lo antes posible.
contactErrorHeader=Error
contactErrorMessage=Hubo un error enviando tu mensaje, inténtalo nuevamente.
headerHeight=35
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
